### ISSUE TITLE
Hook to extend own Twig Filters

### ISSUE THREAD

**Issue by hannehofmann** [cvc-digital/typo3-twig#10]
Hey Markus,

Is it possible to provide an Hook to extend Twig with own filters?

Best Regards,
Hanne

**Comment by markuspoerschke** [comment]
Thanks for rising this topic. I am happy that our extension seems to be used! :)

I already started implemented this, but I did not found time to complete is yet. Currently cou can XCLASS the `\Cvc\Typo3\CvcTwig\Mvc\View\StandaloneView` and modify the `$extensions` property.

**ext_localconf.php:**
```php
$GLOBALS['TYPO3_CONF_VARS']['SYS']['Objects'][\Cvc\Typo3\CvcTwig\Mvc\View\StandaloneView::class] 
    = $GLOBALS['TYPO3_CONF_VARS']['SYS']['Objects'][\MyProjec\MyExtension\Xclass\TwigStandAloneView];
```

**Xclass/TwigStandAlone.php:**
```php
class TwigStandAloneView extends \Cvc\Typo3\CvcTwig\Mvc\View\StandaloneView {

    public function __construct()
    {
        $this->extensions[] = MyTwigExtension::class;
    }
}
```

In future versions there will be an easier and documented way to register Twig extensions. I keep this ticket for this.

**Comment by hannehofmann** [comment]
Hi Markus,

many thanks!!!

BR Hanne

**Comment by markuspoerschke** [comment]
For the version 2 of this extension, I added the documentation here: 

https://github.com/cvc-digital/typo3-twig/commit/ff5e5cc46bc6dd4c032948e110e9638328ee4d67

The Twig Extensions within custom TYPO3 Extensions are added to the Twig Environment automatically now.
