### ISSUE TITLE
Using Twig function t3_uri_page within own extension doesn't seem to work

### ISSUE THREAD

**Issue by MarkusEhrlich** [cvc-digital/typo3-twig#11]
I created an own extension with a new content object (with autoloader extension). Per TS is configured template handling:

plugin.tx_newsletter {
    view {
        templateRootPaths {
            0 = {$plugin.tx_newsletter.view.templateRootPath}
            1 = {$page.twigtemplate.templateRootPath}
        }
    }
}

tt_content.newsletter_newsletter_subscription_widget >
tt_content.newsletter_newsletter_subscription_widget =< lib.twigContentElement
tt_content.newsletter_newsletter_subscription_widget {
    templateName = newsletterSubscriptionWidget.twig
    dataProcessing {
        10 = Namespace... \DataProcessing\NewsletterSubscriptionWidgetProcessor
    }
}

I use follow Twig function inside my template:
<input type="hidden" name="url_ok" value="{{ t3_uri_page(
    additionalParams = {'nls': 'dbo'},
    noCache = true,
    section = 'form-id--newsletter',
    absolute = true
) }}" />

But frontend shows following error:
Call to a member function typoLink_URL() on null

Help is welcome!

**Comment by markuspoerschke** [comment]
Fixed in `1.1.1`
