### ISSUE TITLE
Error when using twig template via typoscript with twig function

### ISSUE THREAD

**Issue by Sonja-Schubert** [cvc-digital/typo3-twig#13]
Hi There,
currently I'm trying to integrate this extension with a simple typoscript template in my TYPO3 V 9.5 introduction package installation. I'm experienced with TYPO3 and Twig but not with twig inside TYPO3 ;-)

Szenario:
I created a new root page with blank typoscript root template and the following typoscript:

page = PAGE
page.10 = TWIGTEMPLATE
page.10 {
    templateName = example.html.twig
    variables {
        foo = TEXT
        foo.value = Bar!
        pageobject = TEXT
        pageobject.data = page:uid
    }
    templateRootPaths {
        10 = EXT:company_twigtemplate/Resources/Private/Templates
    }
}

Of course I installed this extension and added the example.html.twig template in the right place. 

What works:
I can create the sample "Bar!" Output, so twig variable output works.

What does not work:
As soon as I use one of the twig functions provided by the extension eg "{{ t3_uri_page(93) }}" I got an error:

"Call to a member function typoLink_URL() on null"

in /home/vagrant/code/typo3-demo/public/typo3/sysext/extbase/Classes/Mvc/Web/Routing/UriBuilder.php line 712

In this line $this->contentObject is needed which should be a object instance of "\TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer"

Also the promised "data" and "current" vars from the [Getting startet documentation](https://docs.typo3.org/typo3cms/extensions/cvc_twig/stable/Chapters/ContentObject/Index.html) do not output anything.

Do you have an idea what went wrong? Where can I look if everything is loaded by the extension correctly?

Kind regards and thank you for your help

Sonja

**Comment by Sonja-Schubert** [comment]
Hi There,

I tried it again with a completely new installation of typo3/minimal, typo3/cms-tstemplate and cvc/typo3-twig and the typoscript above. The template is again in my own extension Resources folder. Again an output of just a twig var works but t3_uri_page does not with same error messages from above.

So introduction package or it components can not be the cause.

Thank you and kind regards,
Sonja

**Comment by markuspoerschke** [comment]
The bug regarding `{{ t3_uri_page(93) }}` is already fixed in !12, but is not yet merged, because it needs some testing. You could test it installing the branch with `compsoer require cvc/typo3-twig:"dev-bufix-uri-builder"`.

**Comment by markuspoerschke** [comment]
Fixed, will be released with 1.1.1.
