### ISSUE TITLE
UriPage $uriBuilder->reset() is twice

### ISSUE THREAD

**Issue by rbqueo** [cvc-digital/typo3-twig#51]
If pageUid is given to uriPage Extension this will be set but after this the $uriBuilder is nulled via reset(). So the given pageUid has no effect.

Line 81 can be removed and the problem is solved.

**Comment by markuspoerschke** [comment]
@rbqueo Can you have a look at the Merge-Request? https://github.com/cvc-digital/typo3-twig/pull/52
